services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: SoftwareEngineering2022
      MYSQL_DATABASE: elearning_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSoftwareEngineering2022" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/elearning_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: &{{SPRING_DATASOURCE_PASSWORD}}
      JWT_SECRET: &{{JWT_SECRET_KEY}}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elearning-frontend
    environment:
      VITE_API_BASE_URL: http://backend:8080
    ports:
      - "5173:5173"

volumes:
  db-data:
