version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mymysql
    environment:
      MYSQL_ROOT_PASSWORD: SoftwareEngineering2022
      MYSQL_DATABASE: elearning_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile
    container_name: elearning-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/elearning_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SoftwareEngineering2022
      JWT_SECRET_KEY: Drh97bjPEQTiTHdPz4fJTb5lJ5h7VV6EkRWx64aHW8Y0IkkNPQVAam/abO67eu9FcJb+XOueH/en9HpmAsoulg==
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    container_name: elearning-frontend
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db-data:
