import { Code, Database, Smartphone, Palette, BarChart, Megaphone, Camera, Music } from "lucide-react"
import React from "react"

export const categories = [
    {
        name: "Web Development",
        slug: "web-development",
        courseCount: 425,
        icon: React.createElement(Code, { size: 24, className: "text-primary" }),
    },
    {
        name: "Data Science",
        slug: "data-science",
        courseCount: 320,
        icon: React.createElement(Database, { size: 24, className: "text-primary" }),
    },
    {
        name: "Mobile Development",
        slug: "mobile-development",
        courseCount: 275,
        icon: React.createElement(Smartphone, { size: 24, className: "text-primary" }),
    },
    {
        name: "UI/UX Design",
        slug: "ui-ux-design",
        courseCount: 215,
        icon: React.createElement(Palette, { size: 24, className: "text-primary" }),
    },
    {
        name: "Business",
        slug: "business",
        courseCount: 310,
        icon: React.createElement(BarChart, { size: 24, className: "text-primary" }),
    },
    {
        name: "Marketing",
        slug: "marketing",
        courseCount: 290,
        icon: React.createElement(Megaphone, { size: 24, className: "text-primary" }),
    },
    {
        name: "Photography",
        slug: "photography",
        courseCount: 185,
        icon: React.createElement(Camera, { size: 24, className: "text-primary" }),
    },
    {
        name: "Music",
        slug: "music",
        courseCount: 165,
        icon: React.createElement(Music, { size: 24, className: "text-primary" }),
    },
]

export const popularCourses = [
    {
        id: 1,
        title: "The Complete Web Development Bootcamp",
        instructor: "Dr. Angela Yu",
        instructorAvatar: "/confident-instructor.png",
        image: "/placeholder.svg?height=160&width=320&query=web development course",
        price: 19.99,
        originalPrice: 99.99,
        rating: 4.7,
        reviewCount: 154320,
        category: "Web Development",
        level: "Beginner",
        duration: "52 hours",
        enrollments: 850000,
        description:
            "Become a full-stack web developer with just one course. HTML, CSS, Javascript, Node, React, MongoDB, and more!",
    },
    {
        id: 2,
        title: "Machine Learning A-Z: Hands-On Python & R",
        instructor: "Kirill Eremenko",
        instructorAvatar: "/placeholder.svg?height=32&width=32&query=male instructor",
        image: "/placeholder.svg?height=160&width=320&query=machine learning course",
        price: 24.99,
        originalPrice: 129.99,
        rating: 4.5,
        reviewCount: 132450,
        category: "Data Science",
        level: "Intermediate",
        duration: "44 hours",
        enrollments: 720000,
        description: "Learn to create Machine Learning Algorithms in Python and R from two Data Science experts.",
    },
    {
        id: 3,
        title: "React - The Complete Guide (incl Hooks, Redux)",
        instructor: "Maximilian Schwarzmüller",
        instructorAvatar: "/placeholder.svg?height=32&width=32&query=male instructor with glasses",
        image: "/placeholder.svg?height=160&width=320&query=react js course",
        price: 19.99,
        originalPrice: 89.99,
        rating: 4.8,
        reviewCount: 98760,
        category: "Web Development",
        level: "All Levels",
        duration: "48 hours",
        enrollments: 650000,
        description:
            "Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and more!",
    },
    {
        id: 4,
        title: "Flutter & Dart - The Complete Guide",
        instructor: "Maximilian Schwarzmüller",
        instructorAvatar: "/placeholder.svg?height=32&width=32&query=male instructor with glasses",
        image: "/placeholder.svg?height=160&width=320&query=flutter mobile development",
        price: 19.99,
        originalPrice: 89.99,
        rating: 4.6,
        reviewCount: 45670,
        category: "Mobile Development",
        level: "Intermediate",
        duration: "42 hours",
        enrollments: 320000,
        description: "A complete guide to the Flutter SDK & Flutter framework for building native iOS and Android apps.",
    },
]

export const allCourses = [
    ...popularCourses,
    {
        id: 5,
        title: "Python for Data Science and Machine Learning",
        instructor: "Jose Portilla",
        instructorAvatar: "/placeholder.svg?height=32&width=32&query=male instructor with beard",
        image: "/placeholder.svg?height=160&width=320&query=python data science",
        price: 22.99,
        originalPrice: 109.99,
        rating: 4.6,
        reviewCount: 87650,
        category: "Data Science",
        level: "Intermediate",
        duration: "38 hours",
        enrollments: 540000,
        description:
            "Learn how to use NumPy, Pandas, Seaborn, Matplotlib, Plotly, Scikit-Learn, Machine Learning, and more!",
    },
    {
        id: 6,
        title: "UI/UX Design Bootcamp",
        instructor: "Daniel Walter Scott",
        instructorAvatar: "/placeholder.svg?height=32&width=32&query=male instructor smiling",
        image: "/placeholder.svg?height=160&width=320&query=ui ux design",
        price: 24.99,
        originalPrice: 119.99,
        rating: 4.7,
        reviewCount: 32450,
        category: "UI/UX Design",
        level: "Beginner",
        duration: "32 hours",
        enrollments: 280000,
        description:
            "Learn UI/UX design from the ground up. Master Figma, user research, wireframing, prototyping, and more!",
    },
    {
        id: 7,
        title: "The Complete JavaScript Course 2025",
        instructor: "Jonas Schmedtmann",
        instructorAvatar: "/placeholder.svg?height=32&width=32&query=male instructor professional",
        image: "/placeholder.svg?height=160&width=320&query=javascript programming",
        price: 19.99,
        originalPrice: 99.99,
        rating: 4.8,
        reviewCount: 112340,
        category: "Web Development",
        level: "All Levels",
        duration: "69 hours",
        enrollments: 720000,
        description: "The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory.",
    },
    {
        id: 8,
        title: "AWS Certified Solutions Architect",
        instructor: "Stephane Maarek",
        instructorAvatar: "/placeholder.svg?height=32&width=32&query=male instructor tech",
        image: "/placeholder.svg?height=160&width=320&query=aws cloud computing",
        price: 24.99,
        originalPrice: 129.99,
        rating: 4.7,
        reviewCount: 65430,
        category: "Cloud Computing",
        level: "Intermediate",
        duration: "27 hours",
        enrollments: 420000,
        description: "Pass the AWS Solutions Architect Associate Certification. Complete guide with practice exams!",
    },
    {
        id: 9,
        title: "Digital Marketing Masterclass",
        instructor: "Phil Ebiner",
        instructorAvatar: "/placeholder.svg?height=32&width=32&query=male instructor casual",
        image: "/placeholder.svg?height=160&width=320&query=digital marketing",
        price: 19.99,
        originalPrice: 89.99,
        rating: 4.5,
        reviewCount: 43210,
        category: "Marketing",
        level: "Beginner",
        duration: "22 hours",
        enrollments: 350000,
        description:
            "Learn digital marketing strategy, social media marketing, SEO, YouTube, email, Facebook marketing, analytics & more!",
    },
    {
        id: 10,
        title: "iOS & Swift - The Complete iOS App Development Bootcamp",
        instructor: "Dr. Angela Yu",
        instructorAvatar: "/confident-instructor.png",
        image: "/placeholder.svg?height=160&width=320&query=ios swift development",
        price: 24.99,
        originalPrice: 119.99,
        rating: 4.8,
        reviewCount: 54320,
        category: "Mobile Development",
        level: "All Levels",
        duration: "55 hours",
        enrollments: 380000,
        description:
            "From beginner to iOS app developer with just one course. Learn to code and build apps with Swift and Xcode.",
    },
    {
        id: 11,
        title: "The Complete SQL Bootcamp",
        instructor: "Jose Portilla",
        instructorAvatar: "/placeholder.svg?height=32&width=32&query=male instructor with beard",
        image: "/placeholder.svg?height=160&width=320&query=sql database",
        price: 19.99,
        originalPrice: 89.99,
        rating: 4.7,
        reviewCount: 43210,
        category: "Database",
        level: "Beginner",
        duration: "9 hours",
        enrollments: 420000,
        description: "Learn how to use SQL quickly and effectively with this course!",
    },
    {
        id: 12,
        title: "Graphic Design Masterclass",
        instructor: "Lindsay Marsh",
        instructorAvatar: "/placeholder.svg?height=32&width=32&query=female instructor creative",
        image: "/placeholder.svg?height=160&width=320&query=graphic design",
        price: 22.99,
        originalPrice: 109.99,
        rating: 4.6,
        reviewCount: 32450,
        category: "Design",
        level: "All Levels",
        duration: "16 hours",
        enrollments: 280000,
        description: "Learn Graphic Design in this course for beginners. Projects include logos, business cards, and more.",
    },
]
