aon:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

    jobs:
        build:
          runs-on: ubuntu-latest

          steps:
          - name: Check out code
            uses: actions/checkout@v4

          - name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
              java-version: '21'
              distribution: 'temurin'
              cache: maven

          - name: Build with Maven
            run: mvn -B clean package --file pom.xml

          - name: Run tests
            run: mvn test

          - name: Upload build artifact
            uses: actions/upload-artifact@v4
            with:
              name: app-jar
              path: target/*.jar
