name: Build, Test, and Jacoco Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "temurin"

      - name: Build and verify backend
        working-directory: backend
        run: 
          mvn clean package
          mvn test jacoco:report
          mvn verify

      - name: Run tests with Jacoco
        working-directory: backend
        run: mvn test jacoco:report

  frontend-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Run tests
        working-directory: frontend
        run: npx vitest
