name: Build, Test, and Jacoco Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-jacoco:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK for building the project
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "temurin"

      # Build the project using Maven
      - name: Build project
        run: mvn clean install

      # Run tests and generate Jacoco reports
      - name: Run tests with Jacoco
        run: mvn test jacoco:report
