name: Build, Test, and Jacoco Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-jacoco:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK for building the project
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"

      # Build the project using Maven
      - name: Build project
        run: mvn clean package

      # Run tests and generate Jacoco reports
      - name: Run tests with Jacoco
        run: mvn test jacoco:report

      # Upload Jacoco coverage reports as an artifact for later use (optional)
      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco
