name: Build, Test, and Jacoco Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-jacoco:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "temurin"

      - name: Build project
        working-directory: cd backend
        run: mvn clean install

      - name: Run tests with Jacoco
        working-directory: cd backend
        run: mvn test jacoco:report
