name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 (adjust if you use another version)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies to speed up builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project
      - name: Build with Maven
        run: mvn clean install --batch-mode

      # Step 5: Run tests
      - name: Run Tests
        run: mvn test

      # Step 6: Generate JaCoCo test coverage report
      - name: Generate Coverage Report
        run: mvn jacoco:report

      # Step 7: Upload test reports to make them visible in the GitHub Actions UI
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      # Step 8: Upload JaCoCo coverage report (optional, for later viewing or integration)
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/site/jacoco
